version: 0.2

phases:
  install:
    runtime-versions:
      java: "$JAVA_RUNTIME"

  build:
    commands:
      - |
      - mvn clean install -Dskip.unit.tests -P s3-checksums-tests -pl :s3-tests -Dfindbugs.skip -Dcheckstyle.skip -T1C $MAVEN_OPTIONS
      - JAVA_VERSION=$(java -version 2>&1 | grep -i version | cut -d'"' -f2 | cut -d'.' -f1-1)
      - echo $JAVA_VERSION
      - echo $MAVEN_OPTIONS
    finally:
      - mkdir -p codebuild-test-reports
      - find ./ -name 'TEST-*.xml' -type f -exec cp {} codebuild-test-reports/ \;
reports:
  IntegTests:
    files:
      - 'codebuild-test-reports/**/*'
