version: 0.2

phases:
  build:
    commands:
      - mvn clean install -P s3-regression-tests -pl :s3-tests -am -T1C $MAVEN_OPTIONS
      - echo $MAVEN_OPTIONS
    finally:
      - mkdir -p codebuild-test-reports
      - find ./ -name 'TEST-*.xml' -type f -exec cp {} codebuild-test-reports/ \;
reports:
  ChecksumsTests:
    files:
      - 'codebuild-test-reports/**/*'
